Name:           ros-indigo-opencv2
Version:        2.4.9
Release:        2%{?dist}
Summary:        ROS opencv2 package

Group:          Development/Libraries
License:        BSD
URL:            http://opencvg.org
Source0:        %{name}-%{version}.tar.gz

Requires:       ffmpeg-devel
Requires:       jasper-devel
Requires:       libjpeg-turbo-devel
Requires:       libpng-devel
Requires:       numpy
Requires:       python
Requires:       python-devel
Requires:       qt-x11
Requires:       ros-indigo-catkin
Requires:       zlib-devel
BuildRequires:  cmake
BuildRequires:  ffmpeg-devel
BuildRequires:  jasper-devel
BuildRequires:  libjpeg-turbo-devel
BuildRequires:  libpng-devel
BuildRequires:  libtiff
BuildRequires:  libv4l-devel
BuildRequires:  numpy
BuildRequires:  python
BuildRequires:  python-devel
BuildRequires:  qt-devel
BuildRequires:  qt-x11
BuildRequires:  zlib-devel

%description
Cutting edge releases from the opencv 2.4.x.y series.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Sun Sep 14 2014 Daniel Stonier <d.stonier@gmail.com> - 2.4.9-2
- Autogenerated by Bloom

* Sun Sep 14 2014 Daniel Stonier <d.stonier@gmail.com> - 2.4.9-0
- Autogenerated by Bloom

